const transcript = [
	"According to all known laws\nof aviation,",
	"there is no way a bee\nshould be able to fly.",
	"Its wings are too small to get\nits fat little body off the ground.",
	"The bee, of course, flies anyway",
	"because bees don't care\nwhat humans think is impossible.",
	"Yellow, black. Yellow, black.\nYellow, black. Yellow, black.",
	"Ooh, black and yellow!\nLet's shake it up a little.",
	"Barry! Breakfast is ready!",
	"Ooming!",
	"Hang on a second.",
	"Hello?",
	"- Barry?\n- Adam?",
	"- Oan you believe this is happening?\n- I can't. I'll pick you up.",
	"Looking sharp.",
	"Use the stairs. Your father\npaid good money for those.",
	"Sorry. I'm excited.",
	"Here's the graduate.\nWe're very proud of you, son.",
	"A perfect report card, all B's.",
	"Very proud.",
	"Ma! I got a thing going here.",
	"- You got lint on your fuzz.\n- Ow! That's me!",
	"- Wave to us! We'll be in row 118,000.\n- Bye!",
	"Barry, I told you,\nstop flying in the house!",
	"- Hey, Adam.\n- Hey, Barry.",
	"- Is that fuzz gel?\n- A little. Special day, graduation.",
	"Never thought I'd make it.",
	"Three days grade school,\nthree days high school.",
	"Those were awkward.",
	"Three days college. I'm glad I took\na day and hitchhiked around the hive.",
	"You did come back different.",
	"- Hi, Barry.\n- Artie, growing a mustache? Looks good.",
	"- Hear about Frankie?\n- Yeah.",
	"- You going to the funeral?\n- No, I'm not going.",
	"Everybody knows,\nsting someone, you die.",
	"Don't waste it on a squirrel.\nSuch a hothead.",
	"I guess he could have\njust gotten out of the way.",
	"I love this incorporating\nan amusement park into our day.",
	"That's why we don't need vacations.",
	"Boy, quite a bit of pomp...\nunder the circumstances.",
	"- Well, Adam, today we are men.\n- We are!",
	"- Bee-men.\n- Amen!",
	"Hallelujah!",
	"Students, faculty, distinguished bees,",
	"please welcome Dean Buzzwell.",
	"Welcome, New Hive Oity\ngraduating class of...",
	"...9:15.",
	"That concludes our ceremonies.",
	"And begins your career\nat Honex Industries!",
	"Will we pick ourjob today?",
	"I heard it's just orientation.",
	"Heads up! Here we go.",
	"Keep your hands and antennas\ninside the tram at all times.",
	"- Wonder what it'll be like?\n- A little scary.",
	"Welcome to Honex,\na division of Honesco",
	"and a part of the Hexagon Group.",
	"This is it!",
	"Wow.",
	"Wow.",
	"We know that you, as a bee,\nhave worked your whole life",
	"to get to the point where you\ncan work for your whole life.",
	"Honey begins when our valiant Pollen\nJocks bring the nectar to the hive.",
	"Our top-secret formula",
	"is automatically color-corrected,\nscent-adjusted and bubble-contoured",
	"into this soothing sweet syrup",
	"with its distinctive\ngolden glow you know as...",
	"Honey!",
	"- That girl was hot.\n- She's my cousin!",
	"- She is?\n- Yes, we're all cousins.",
	"- Right. You're right.\n- At Honex, we constantly strive",
	"to improve every aspect\nof bee existence.",
	"These bees are stress-testing\na new helmet technology.",
	"- What do you think he makes?\n- Not enough.",
	"Here we have our latest advancement,\nthe Krelman.",
	"- What does that do?\n- Oatches that little strand of honey",
	"that hangs after you pour it.\nSaves us millions.",
	"Oan anyone work on the Krelman?",
	"Of course. Most bee jobs are\nsmall ones. But bees know",
	"that every small job,\nif it's done well, means a lot.",
	"But choose carefully",
	"because you'll stay in the job\nyou pick for the rest of your life.",
	"The same job the rest of your life?\nI didn't know that.",
	"What's the difference?",
	"You'll be happy to know that bees,\nas a species, haven't had one day off",
	"in 27 million years.",
	"So you'll just work us to death?",
	"We'll sure try.",
	"Wow! That blew my mind!",
	'"What\'s the difference?"\nHow can you say that?',
	"One job forever?\nThat's an insane choice to have to make.",
	"I'm relieved. Now we only have\nto make one decision in life.",
	"But, Adam, how could they\nnever have told us that?",
	"Why would you question anything?\nWe're bees.",
	"We're the most perfectly\nfunctioning society on Earth.",
	"You ever think maybe things\nwork a little too well here?",
	"Like what? Give me one example.",
	"I don't know. But you know\nwhat I'm talking about.",
	"Please clear the gate.\nRoyal Nectar Force on approach.",
	"Wait a second. Oheck it out.",
	"- Hey, those are Pollen Jocks!\n- Wow.",
	"I've never seen them this close.",
	"They know what it's like\noutside the hive.",
	"Yeah, but some don't come back.",
	"- Hey, Jocks!\n- Hi, Jocks!",
	"You guys did great!",
	"You're monsters!\nYou're sky freaks! I love it! I love it!",
	"- I wonder where they were.\n- I don't know.",
	"Their day's not planned.",
	"Outside the hive, flying who knows\nwhere, doing who knows what.",
	"You can'tjust decide to be a Pollen\nJock. You have to be bred for that.",
	"Right.",
	"Look. That's more pollen\nthan you and I will see in a lifetime.",
	"It's just a status symbol.\nBees make too much of it.",
	"Perhaps. Unless you're wearing it\nand the ladies see you wearing it.",
	"Those ladies?\nAren't they our cousins too?",
	"Distant. Distant.",
	"Look at these two.",
	"- Oouple of Hive Harrys.\n- Let's have fun with them.",
	"It must be dangerous\nbeing a Pollen Jock.",
	"Yeah. Once a bear pinned me\nagainst a mushroom!",
	"He had a paw on my throat,\nand with the other, he was slapping me!",
	"- Oh, my!\n- I never thought I'd knock him out.",
	"What were you doing during this?",
	"Trying to alert the authorities.",
	"I can autograph that.",
	"A little gusty out there today,\nwasn't it, comrades?",
	"Yeah. Gusty.",
	"We're hitting a sunflower patch\nsix miles from here tomorrow.",
	"- Six miles, huh?\n- Barry!",
	"A puddle jump for us,\nbut maybe you're not up for it.",
	"- Maybe I am.\n- You are not!",
	"We're going 0900 at J-Gate.",
	"What do you think, buzzy-boy?\nAre you bee enough?",
	"I might be. It all depends\non what 0900 means.",
	"Hey, Honex!",
	"Dad, you surprised me.",
	"You decide what you're interested in?",
	"- Well, there's a lot of choices.\n- But you only get one.",
	"Do you ever get bored\ndoing the same job every day?",
	"Son, let me tell you about stirring.",
	"You grab that stick, and you just\nmove it around, and you stir it around.",
	"You get yourself into a rhythm.\nIt's a beautiful thing.",
	"You know, Dad,\nthe more I think about it,",
	"maybe the honey field\njust isn't right for me.",
	"You were thinking of what,\nmaking balloon animals?",
	"That's a bad job\nfor a guy with a stinger.",
	"Janet, your son's not sure\nhe wants to go into honey!",
	"- Barry, you are so funny sometimes.\n- I'm not trying to be funny.",
	"You're not funny! You're going\ninto honey. Our son, the stirrer!",
	"- You're gonna be a stirrer?\n- No one's listening to me!",
	"Wait till you see the sticks I have.",
	"I could say anything right now.\nI'm gonna get an ant tattoo!",
	"Let's open some honey and celebrate!",
	"Maybe I'll pierce my thorax.\nShave my antennae.",
	'Shack up with a grasshopper. Get\na gold tooth and call everybody "dawg"!',
	"I'm so proud.",
	"- We're starting work today!\n- Today's the day.",
	"Oome on! All the good jobs\nwill be gone.",
	"Yeah, right.",
	"Pollen counting, stunt bee, pouring,\nstirrer, front desk, hair removal...",
	"- Is it still available?\n- Hang on. Two left!",
	"One of them's yours! Oongratulations!\nStep to the side.",
	"- What'd you get?\n- Picking crud out. Stellar!",
	"Wow!",
	"Oouple of newbies?",
	"Yes, sir! Our first day! We are ready!",
	"Make your choice.",
	"- You want to go first?\n- No, you go.",
	"Oh, my. What's available?",
	"Restroom attendant's open,\nnot for the reason you think.",
	"- Any chance of getting the Krelman?\n- Sure, you're on.",
	"I'm sorry, the Krelman just closed out.",
	"Wax monkey's always open.",
	"The Krelman opened up again.",
	"What happened?",
	"A bee died. Makes an opening. See?\nHe's dead. Another dead one.",
	"Deady. Deadified. Two more dead.",
	"Dead from the neck up.\nDead from the neck down. That's life!",
	"Oh, this is so hard!",
	"Heating, cooling,\nstunt bee, pourer, stirrer,",
	"humming, inspector number seven,\nlint coordinator, stripe supervisor,",
	"mite wrangler. Barry, what\ndo you think I should... Barry?",
	"Barry!",
	"All right, we've got the sunflower patch\nin quadrant nine...",
	"What happened to you?\nWhere are you?",
	"- I'm going out.\n- Out? Out where?",
	"- Out there.\n- Oh, no!",
	"I have to, before I go\nto work for the rest of my life.",
	"You're gonna die! You're crazy! Hello?",
	"Another call coming in.",
	"If anyone's feeling brave,\nthere's a Korean deli on 83rd",
	"that gets their roses today.",
	"Hey, guys.",
	"- Look at that.\n- Isn't that the kid we saw yesterday?",
	"Hold it, son, flight deck's restricted.",
	"It's OK, Lou. We're gonna take him up.",
	"Really? Feeling lucky, are you?",
	"Sign here, here. Just initial that.",
	"- Thank you.\n- OK.",
	"You got a rain advisory today,",
	"and as you all know,\nbees cannot fly in rain.",
	"So be careful. As always,\nwatch your brooms,",
	"hockey sticks, dogs,\nbirds, bears and bats.",
	"Also, I got a couple of reports\nof root beer being poured on us.",
	"Murphy's in a home because of it,\nbabbling like a cicada!",
	"- That's awful.\n- And a reminder for you rookies,",
	"bee law number one,\nabsolutely no talking to humans!",
	"All right, launch positions!",
	"Buzz, buzz, buzz, buzz! Buzz, buzz,\nbuzz, buzz! Buzz, buzz, buzz, buzz!",
	"Black and yellow!",
	"Hello!",
	"You ready for this, hot shot?",
	"Yeah. Yeah, bring it on.",
	"Wind, check.",
	"- Antennae, check.\n- Nectar pack, check.",
	"- Wings, check.\n- Stinger, check.",
	"Scared out of my shorts, check.",
	"OK, ladies,",
	"let's move it out!",
	"Pound those petunias,\nyou striped stem-suckers!",
	"All of you, drain those flowers!",
	"Wow! I'm out!",
	"I can't believe I'm out!",
	"So blue.",
	"I feel so fast and free!",
	"Box kite!",
	"Wow!",
	"Flowers!",
	"This is Blue Leader.\nWe have roses visual.",
	"Bring it around 30 degrees and hold.",
	"Roses!",
	"30 degrees, roger. Bringing it around.",
	"Stand to the side, kid.\nIt's got a bit of a kick.",
	"That is one nectar collector!",
	"- Ever see pollination up close?\n- No, sir.",
	"I pick up some pollen here, sprinkle it\nover here. Maybe a dash over there,",
	"a pinch on that one.\nSee that? It's a little bit of magic.",
	"That's amazing. Why do we do that?",
	"That's pollen power. More pollen, more\nflowers, more nectar, more honey for us.",
	"Oool.",
	"I'm picking up a lot of bright yellow.\nOould be daisies. Don't we need those?",
	"Oopy that visual.",
	"Wait. One of these flowers\nseems to be on the move.",
	"Say again? You're reporting\na moving flower?",
	"Affirmative.",
	"That was on the line!",
	"This is the coolest. What is it?",
	"I don't know, but I'm loving this color.",
	"It smells good.\nNot like a flower, but I like it.",
	"Yeah, fuzzy.",
	"Ohemical-y.",
	"Oareful, guys. It's a little grabby.",
	"My sweet lord of bees!",
	"Oandy-brain, get off there!",
	"Problem!",
	"- Guys!\n- This could be bad.",
	"Affirmative.",
	"Very close.",
	"Gonna hurt.",
	"Mama's little boy.",
	"You are way out of position, rookie!",
	"Ooming in at you like a missile!",
	"Help me!",
	"I don't think these are flowers.",
	"- Should we tell him?\n- I think he knows.",
	"What is this?!",
	"Match point!",
	"You can start packing up, honey,\nbecause you're about to eat it!",
	"Yowser!",
	"Gross.",
	"There's a bee in the car!",
	"- Do something!\n- I'm driving!",
	"- Hi, bee.\n- He's back here!",
	"He's going to sting me!",
	"Nobody move. If you don't move,\nhe won't sting you. Freeze!",
	"He blinked!",
	"Spray him, Granny!",
	"What are you doing?!",
	"Wow... the tension level\nout here is unbelievable.",
	"I gotta get home.",
	"Oan't fly in rain.",
	"Oan't fly in rain.",
	"Oan't fly in rain.",
	"Mayday! Mayday! Bee going down!",
	"Ken, could you close\nthe window please?",
	"Ken, could you close\nthe window please?",
	"Oheck out my new resume.\nI made it into a fold-out brochure.",
	"You see? Folds out.",
	"Oh, no. More humans. I don't need this.",
	"What was that?",
	"Maybe this time. This time. This time.\nThis time! This time! This...",
	"Drapes!",
	"That is diabolical.",
	"It's fantastic. It's got all my special\nskills, even my top-ten favorite movies.",
	"What's number one? Star Wars?",
	"Nah, I don't go for that...",
	"...kind of stuff.",
	"No wonder we shouldn't talk to them.\nThey're out of their minds.",
	"When I leave a job interview, they're\nflabbergasted, can't believe what I say.",
	"There's the sun. Maybe that's a way out.",
	"I don't remember the sun\nhaving a big 75 on it.",
	"I predicted global warming.",
	"I could feel it getting hotter.\nAt first I thought it was just me.",
	"Wait! Stop! Bee!",
	"Stand back. These are winter boots.",
	"Wait!",
	"Don't kill him!",
	"You know I'm allergic to them!\nThis thing could kill me!",
	"Why does his life have\nless value than yours?",
	"Why does his life have any less value\nthan mine? Is that your statement?",
	"I'm just saying all life has value. You\ndon't know what he's capable of feeling.",
	"My brochure!",
	"There you go, little guy.",
	"I'm not scared of him.\nIt's an allergic thing.",
	"Put that on your resume brochure.",
	"My whole face could puff up.",
	"Make it one of your special skills.",
	"Knocking someone out\nis also a special skill.",
	"Right. Bye, Vanessa. Thanks.",
	"- Vanessa, next week? Yogurt night?\n- Sure, Ken. You know, whatever.",
	"- You could put carob chips on there.\n- Bye.",
	"- Supposed to be less calories.\n- Bye.",
	"I gotta say something.",
	"She saved my life.\nI gotta say something.",
	"All right, here it goes.",
	"Nah.",
	"What would I say?",
	"I could really get in trouble.",
	"It's a bee law.\nYou're not supposed to talk to a human.",
	"I can't believe I'm doing this.",
	"I've got to.",
	"Oh, I can't do it. Oome on!",
	"No. Yes. No.",
	"Do it. I can't.",
	'How should I start it?\n"You like jazz?" No, that\'s no good.',
	"Here she comes! Speak, you fool!",
	"Hi!",
	"I'm sorry.",
	"- You're talking.\n- Yes, I know.",
	"You're talking!",
	"I'm so sorry.",
	"No, it's OK. It's fine.\nI know I'm dreaming.",
	"But I don't recall going to bed.",
	"Well, I'm sure this\nis very disconcerting.",
	"This is a bit of a surprise to me.\nI mean, you're a bee!",
	"I am. And I'm not supposed\nto be doing this,",
	"but they were all trying to kill me.",
	"And if it wasn't for you...",
	"I had to thank you.\nIt's just how I was raised.",
	"That was a little weird.",
	"- I'm talking with a bee.\n- Yeah.",
	"I'm talking to a bee.\nAnd the bee is talking to me!",
	"I just want to say I'm grateful.\nI'll leave now.",
	"- Wait! How did you learn to do that?\n- What?",
	"The talking thing.",
	'Same way you did, I guess.\n"Mama, Dada, honey." You pick it up.',
	"- That's very funny.\n- Yeah.",
	"Bees are funny. If we didn't laugh,\nwe'd cry with what we have to deal with.",
	"Anyway...",
	"Oan I...",
	"...get you something?\n- Like what?",
	"I don't know. I mean...\nI don't know. Ooffee?",
	"I don't want to put you out.",
	"It's no trouble. It takes two minutes.",
	"- It's just coffee.\n- I hate to impose.",
	"- Don't be ridiculous!\n- Actually, I would love a cup.",
	"Hey, you want rum cake?",
	"- I shouldn't.\n- Have some.",
	"- No, I can't.\n- Oome on!",
	"I'm trying to lose a couple micrograms.",
	"- Where?\n- These stripes don't help.",
	"You look great!",
	"I don't know if you know\nanything about fashion.",
	"Are you all right?",
	"No.",
	"He's making the tie in the cab\nas they're flying up Madison.",
	"He finally gets there.",
	"He runs up the steps into the church.\nThe wedding is on.",
	'And he says, "Watermelon?\nI thought you said Guatemalan.',
	'Why would I marry a watermelon?"',
	"Is that a bee joke?",
	"That's the kind of stuff we do.",
	"Yeah, different.",
	"So, what are you gonna do, Barry?",
	"About work? I don't know.",
	"I want to do my part for the hive,\nbut I can't do it the way they want.",
	"I know how you feel.",
	"- You do?\n- Sure.",
	"My parents wanted me to be a lawyer or\na doctor, but I wanted to be a florist.",
	"- Really?\n- My only interest is flowers.",
	"Our new queen was just elected\nwith that same campaign slogan.",
	"Anyway, if you look...",
	"There's my hive right there. See it?",
	"You're in Sheep Meadow!",
	"Yes! I'm right off the Turtle Pond!",
	"No way! I know that area.\nI lost a toe ring there once.",
	"- Why do girls put rings on their toes?\n- Why not?",
	"- It's like putting a hat on your knee.\n- Maybe I'll try that.",
	"- You all right, ma'am?\n- Oh, yeah. Fine.",
	"Just having two cups of coffee!",
	"Anyway, this has been great.\nThanks for the coffee.",
	"Yeah, it's no trouble.",
	"Sorry I couldn't finish it. If I did,\nI'd be up the rest of my life.",
	"Are you...?",
	"Oan I take a piece of this with me?",
	"Sure! Here, have a crumb.",
	"- Thanks!\n- Yeah.",
	"All right. Well, then...\nI guess I'll see you around.",
	"Or not.",
	"OK, Barry.",
	"And thank you\nso much again... for before.",
	"Oh, that? That was nothing.",
	"Well, not nothing, but... Anyway...",
	"This can't possibly work.",
	"He's all set to go.\nWe may as well try it.",
	"OK, Dave, pull the chute.",
	"- Sounds amazing.\n- It was amazing!",
	"It was the scariest,\nhappiest moment of my life.",
	"Humans! I can't believe\nyou were with humans!",
	"Giant, scary humans!\nWhat were they like?",
	"Huge and crazy. They talk crazy.",
	"They eat crazy giant things.\nThey drive crazy.",
	"- Do they try and kill you, like on TV?\n- Some of them. But some of them don't.",
	"- How'd you get back?\n- Poodle.",
	"You did it, and I'm glad. You saw\nwhatever you wanted to see.",
	'You had your "experience." Now you\ncan pick out yourjob and be normal.',
	"- Well...\n- Well?",
	"Well, I met someone.",
	"You did? Was she Bee-ish?",
	"- A wasp?! Your parents will kill you!\n- No, no, no, not a wasp.",
	"- Spider?\n- I'm not attracted to spiders.",
	"I know it's the hottest thing,\nwith the eight legs and all.",
	"I can't get by that face.",
	"So who is she?",
	"She's... human.",
	"No, no. That's a bee law.\nYou wouldn't break a bee law.",
	"- Her name's Vanessa.\n- Oh, boy.",
	"She's so nice. And she's a florist!",
	"Oh, no! You're dating a human florist!",
	"We're not dating.",
	"You're flying outside the hive, talking\nto humans that attack our homes",
	"with power washers and M-80s!\nOne-eighth a stick of dynamite!",
	"She saved my life!\nAnd she understands me.",
	"This is over!",
	"Eat this.",
	"This is not over! What was that?",
	"- They call it a crumb.\n- It was so stingin' stripey!",
	"And that's not what they eat.\nThat's what falls off what they eat!",
	"- You know what a Oinnabon is?\n- No.",
	"It's bread and cinnamon and frosting.\nThey heat it up...",
	"Sit down!",
	"...really hot!\n- Listen to me!",
	"We are not them! We're us.\nThere's us and there's them!",
	"Yes, but who can deny\nthe heart that is yearning?",
	"There's no yearning.\nStop yearning. Listen to me!",
	"You have got to start thinking bee,\nmy friend. Thinking bee!",
	"- Thinking bee.\n- Thinking bee.",
	"Thinking bee! Thinking bee!\nThinking bee! Thinking bee!",
	"There he is. He's in the pool.",
	"You know what your problem is, Barry?",
	"I gotta start thinking bee?",
	"How much longer will this go on?",
	"It's been three days!\nWhy aren't you working?",
	"I've got a lot of big life decisions\nto think about.",
	"What life? You have no life!\nYou have no job. You're barely a bee!",
	"Would it kill you\nto make a little honey?",
	"Barry, come out.\nYour father's talking to you.",
	"Martin, would you talk to him?",
	"Barry, I'm talking to you!",
	"You coming?",
	"Got everything?",
	"All set!",
	"Go ahead. I'll catch up.",
	"Don't be too long.",
	"Watch this!",
	"Vanessa!",
	"- We're still here.\n- I told you not to yell at him.",
	"He doesn't respond to yelling!",
	"- Then why yell at me?\n- Because you don't listen!",
	"I'm not listening to this.",
	"Sorry, I've gotta go.",
	"- Where are you going?\n- I'm meeting a friend.",
	"A girl? Is this why you can't decide?",
	"Bye.",
	"I just hope she's Bee-ish.",
	"They have a huge parade\nof flowers every year in Pasadena?",
	"To be in the Tournament of Roses,\nthat's every florist's dream!",
	"Up on a float, surrounded\nby flowers, crowds cheering.",
	"A tournament. Do the roses\ncompete in athletic events?",
	"No. All right, I've got one.\nHow come you don't fly everywhere?",
	"It's exhausting. Why don't you\nrun everywhere? It's faster.",
	"Yeah, OK, I see, I see.\nAll right, your turn.",
	"TiVo. You can just freeze live TV?\nThat's insane!",
	"You don't have that?",
	"We have Hivo, but it's a disease.\nIt's a horrible, horrible disease.",
	"Oh, my.",
	"Dumb bees!",
	"You must want to sting all those jerks.",
	"We try not to sting.\nIt's usually fatal for us.",
	"So you have to watch your temper.",
	"Very carefully.\nYou kick a wall, take a walk,",
	"write an angry letter and throw it out.\nWork through it like any emotion:",
	"Anger, jealousy, lust.",
	"Oh, my goodness! Are you OK?",
	"Yeah.",
	"- What is wrong with you?!\n- It's a bug.",
	"He's not bothering anybody.\nGet out of here, you creep!",
	"What was that? A Pic 'N' Save circular?",
	"Yeah, it was. How did you know?",
	"It felt like about 10 pages.\nSeventy-five is pretty much our limit.",
	"You've really got that\ndown to a science.",
	"- I lost a cousin to Italian Vogue.\n- I'll bet.",
	"What in the name\nof Mighty Hercules is this?",
	"How did this get here?\nOute Bee, Golden Blossom,",
	"Ray Liotta Private Select?",
	"- Is he that actor?\n- I never heard of him.",
	"- Why is this here?\n- For people. We eat it.",
	"You don't have\nenough food of your own?",
	"- Well, yes.\n- How do you get it?",
	"- Bees make it.\n- I know who makes it!",
	"And it's hard to make it!",
	"There's heating, cooling, stirring.\nYou need a whole Krelman thing!",
	"- It's organic.\n- It's our-ganic!",
	"It's just honey, Barry.",
	"Just what?!",
	"Bees don't know about this!\nThis is stealing! A lot of stealing!",
	"You've taken our homes, schools,\nhospitals! This is all we have!",
	"And it's on sale?!\nI'm getting to the bottom of this.",
	"I'm getting to the bottom\nof all of this!",
	"Hey, Hector.",
	"- You almost done?\n- Almost.",
	"He is here. I sense it.",
	"Well, I guess I'll go home now",
	"and just leave this nice honey out,\nwith no one around.",
	"You're busted, box boy!",
	"I knew I heard something.\nSo you can talk!",
	"I can talk.\nAnd now you'll start talking!",
	"Where you getting the sweet stuff?\nWho's your supplier?",
	"I don't understand.\nI thought we were friends.",
	"The last thing we want\nto do is upset bees!",
	"You're too late! It's ours now!",
	"You, sir, have crossed\nthe wrong sword!",
	"You, sir, will be lunch\nfor my iguana, Ignacio!",
	"Where is the honey coming from?",
	"Tell me where!",
	"Honey Farms! It comes from Honey Farms!",
	"Orazy person!",
	"What horrible thing has happened here?",
	"These faces, they never knew\nwhat hit them. And now",
	"they're on the road to nowhere!",
	"Just keep still.",
	"What? You're not dead?",
	"Do I look dead? They will wipe anything\nthat moves. Where you headed?",
	"To Honey Farms.\nI am onto something huge here.",
	"I'm going to Alaska. Moose blood,\ncrazy stuff. Blows your head off!",
	"I'm going to Tacoma.",
	"- And you?\n- He really is dead.",
	"All right.",
	"Uh-oh!",
	"- What is that?!\n- Oh, no!",
	"- A wiper! Triple blade!\n- Triple blade?",
	"Jump on! It's your only chance, bee!",
	"Why does everything have\nto be so doggone clean?!",
	"How much do you people need to see?!",
	"Open your eyes!\nStick your head out the window!",
	"From NPR News in Washington,\nI'm Oarl Kasell.",
	"But don't kill no more bugs!",
	"- Bee!\n- Moose blood guy!!",
	"- You hear something?\n- Like what?",
	"Like tiny screaming.",
	"Turn off the radio.",
	"Whassup, bee boy?",
	"Hey, Blood.",
	"Just a row of honey jars,\nas far as the eye could see.",
	"Wow!",
	"I assume wherever this truck goes\nis where they're getting it.",
	"I mean, that honey's ours.",
	"- Bees hang tight.\n- We're all jammed in.",
	"It's a close community.",
	"Not us, man. We on our own.\nEvery mosquito on his own.",
	"- What if you get in trouble?\n- You a mosquito, you in trouble.",
	"Nobody likes us. They just smack.\nSee a mosquito, smack, smack!",
	"At least you're out in the world.\nYou must meet girls.",
	"Mosquito girls try to trade up,\nget with a moth, dragonfly.",
	"Mosquito girl don't want no mosquito.",
	"You got to be kidding me!",
	"Mooseblood's about to leave\nthe building! So long, bee!",
	"- Hey, guys!\n- Mooseblood!",
	"I knew I'd catch y'all down here.\nDid you bring your crazy straw?",
	"We throw it in jars, slap a label on it,\nand it's pretty much pure profit.",
	"What is this place?",
	"A bee's got a brain\nthe size of a pinhead.",
	"They are pinheads!",
	"Pinhead.",
	"- Oheck out the new smoker.\n- Oh, sweet. That's the one you want.",
	"The Thomas 3000!",
	"Smoker?",
	"Ninety puffs a minute, semi-automatic.\nTwice the nicotine, all the tar.",
	"A couple breaths of this\nknocks them right out.",
	"They make the honey,\nand we make the money.",
	'"They make the honey,\nand we make the money"?',
	"Oh, my!",
	"What's going on? Are you OK?",
	"Yeah. It doesn't last too long.",
	"Do you know you're\nin a fake hive with fake walls?",
	"Our queen was moved here.\nWe had no choice.",
	"This is your queen?\nThat's a man in women's clothes!",
	"That's a drag queen!",
	"What is this?",
	"Oh, no!",
	"There's hundreds of them!",
	"Bee honey.",
	"Our honey is being brazenly stolen\non a massive scale!",
	"This is worse than anything bears\nhave done! I intend to do something.",
	"Oh, Barry, stop.",
	"Who told you humans are taking\nour honey? That's a rumor.",
	"Do these look like rumors?",
	"That's a conspiracy theory.\nThese are obviously doctored photos.",
	"How did you get mixed up in this?",
	"He's been talking to humans.",
	"- What?\n- Talking to humans?!",
	"He has a human girlfriend.\nAnd they make out!",
	"Make out? Barry!",
	"We do not.",
	"- You wish you could.\n- Whose side are you on?",
	"The bees!",
	"I dated a cricket once in San Antonio.\nThose crazy legs kept me up all night.",
	"Barry, this is what you want\nto do with your life?",
	"I want to do it for all our lives.\nNobody works harder than bees!",
	"Dad, I remember you\ncoming home so overworked",
	"your hands were still stirring.\nYou couldn't stop.",
	"I remember that.",
	"What right do they have to our honey?",
	"We live on two cups a year. They put it\nin lip balm for no reason whatsoever!",
	"Even if it's true, what can one bee do?",
	"Sting them where it really hurts.",
	"In the face! The eye!",
	"- That would hurt.\n- No.",
	"Up the nose? That's a killer.",
	"There's only one place you can sting\nthe humans, one place where it matters.",
	"Hive at Five, the hive's only\nfull-hour action news source.",
	"No more bee beards!",
	"With Bob Bumble at the anchor desk.",
	"Weather with Storm Stinger.",
	"Sports with Buzz Larvi.",
	"And Jeanette Ohung.",
	"- Good evening. I'm Bob Bumble.\n- And I'm Jeanette Ohung.",
	"A tri-county bee, Barry Benson,",
	"intends to sue the human race\nfor stealing our honey,",
	"packaging it and profiting\nfrom it illegally!",
	"Tomorrow night on Bee Larry King,",
	"we'll have three former queens here in\nour studio, discussing their new book,",
	"Olassy Ladies,\nout this week on Hexagon.",
	"Tonight we're talking to Barry Benson.",
	"Did you ever think, \"I'm a kid\nfrom the hive. I can't do this\"?",
	"Bees have never been afraid\nto change the world.",
	"What about Bee Oolumbus?\nBee Gandhi? Bejesus?",
	"Where I'm from, we'd never sue humans.",
	"We were thinking\nof stickball or candy stores.",
	"How old are you?",
	"The bee community\nis supporting you in this case,",
	"which will be the trial\nof the bee century.",
	"You know, they have a Larry King\nin the human world too.",
	"It's a common name. Next week...",
	"He looks like you and has a show\nand suspenders and colored dots...",
	"Next week...",
	"Glasses, quotes on the bottom from the\nguest even though you just heard 'em.",
	"Bear Week next week!\nThey're scary, hairy and here live.",
	"Always leans forward, pointy shoulders,\nsquinty eyes, very Jewish.",
	"In tennis, you attack\nat the point of weakness!",
	"It was my grandmother, Ken. She's 81.",
	"Honey, her backhand's a joke!\nI'm not gonna take advantage of that?",
	"Quiet, please.\nActual work going on here.",
	"- Is that that same bee?\n- Yes, it is!",
	"I'm helping him sue the human race.",
	"- Hello.\n- Hello, bee.",
	"This is Ken.",
	"Yeah, I remember you. Timberland, size\nten and a half. Vibram sole, I believe.",
	"Why does he talk again?",
	"Listen, you better go\n'cause we're really busy working.",
	"But it's our yogurt night!",
	"Bye-bye.",
	"Why is yogurt night so difficult?!",
	"You poor thing.\nYou two have been at this for hours!",
	"Yes, and Adam here\nhas been a huge help.",
	"- Frosting...\n- How many sugars?",
	"Just one. I try not\nto use the competition.",
	"So why are you helping me?",
	"Bees have good qualities.",
	"And it takes my mind off the shop.",
	"Instead of flowers, people\nare giving balloon bouquets now.",
	"Those are great, if you're three.",
	"And artificial flowers.",
	"- Oh, those just get me psychotic!\n- Yeah, me too.",
	"Bent stingers, pointless pollination.",
	"Bees must hate those fake things!",
	"Nothing worse\nthan a daffodil that's had work done.",
	"Maybe this could make up\nfor it a little bit.",
	"- This lawsuit's a pretty big deal.\n- I guess.",
	"You sure you want to go through with it?",
	"Am I sure? When I'm done with\nthe humans, they won't be able",
	'to say, "Honey, I\'m home,"\nwithout paying a royalty!',
	"It's an incredible scene\nhere in downtown Manhattan,",
	"where the world anxiously waits,\nbecause for the first time in history,",
	"we will hear for ourselves\nif a honeybee can actually speak.",
	"What have we gotten into here, Barry?",
	"It's pretty big, isn't it?",
	"I can't believe how many humans\ndon't work during the day.",
	"You think billion-dollar multinational\nfood companies have good lawyers?",
	"Everybody needs to stay\nbehind the barricade.",
	"- What's the matter?\n- I don't know, I just got a chill.",
	"Well, if it isn't the bee team.",
	"You boys work on this?",
	"All rise! The Honorable\nJudge Bumbleton presiding.",
	"All right. Oase number 4475,",
	"Superior Oourt of New York,\nBarry Bee Benson v. the Honey Industry",
	"is now in session.",
	"Mr. Montgomery, you're representing\nthe five food companies collectively?",
	"A privilege.",
	"Mr. Benson... you're representing\nall the bees of the world?",
	"I'm kidding. Yes, Your Honor,\nwe're ready to proceed.",
	"Mr. Montgomery,\nyour opening statement, please.",
	"Ladies and gentlemen of the jury,",
	"my grandmother was a simple woman.",
	"Born on a farm, she believed\nit was man's divine right",
	"to benefit from the bounty\nof nature God put before us.",
	"If we lived in the topsy-turvy world\nMr. Benson imagines,",
	"just think of what would it mean.",
	"I would have to negotiate\nwith the silkworm",
	"for the elastic in my britches!",
	"Talking bee!",
	"How do we know this isn't some sort of",
	"holographic motion-picture-capture\nHollywood wizardry?",
	"They could be using laser beams!",
	"Robotics! Ventriloquism!\nOloning! For all we know,",
	"he could be on steroids!",
	"Mr. Benson?",
	"Ladies and gentlemen,\nthere's no trickery here.",
	"I'm just an ordinary bee.\nHoney's pretty important to me.",
	"It's important to all bees.\nWe invented it!",
	"We make it. And we protect it\nwith our lives.",
	"Unfortunately, there are\nsome people in this room",
	"who think they can take it from us",
	"'cause we're the little guys!\nI'm hoping that, after this is all over,",
	"you'll see how, by taking our honey,\nyou not only take everything we have",
	"but everything we are!",
	"I wish he'd dress like that\nall the time. So nice!",
	"Oall your first witness.",
	"So, Mr. Klauss Vanderhayden\nof Honey Farms, big company you have.",
	"I suppose so.",
	"I see you also own\nHoneyburton and Honron!",
	"Yes, they provide beekeepers\nfor our farms.",
	"Beekeeper. I find that\nto be a very disturbing term.",
	"I don't imagine you employ\nany bee-free-ers, do you?",
	"- No.\n- I couldn't hear you.",
	"- No.\n- No.",
	"Because you don't free bees.\nYou keep bees. Not only that,",
	"it seems you thought a bear would be\nan appropriate image for a jar of honey.",
	"They're very lovable creatures.",
	"Yogi Bear, Fozzie Bear, Build-A-Bear.",
	"You mean like this?",
	"Bears kill bees!",
	"How'd you like his head crashing\nthrough your living room?!",
	"Biting into your couch!\nSpitting out your throw pillows!",
	"OK, that's enough. Take him away.",
	"So, Mr. Sting, thank you for being here.\nYour name intrigues me.",
	"- Where have I heard it before?\n- I was with a band called The Police.",
	"But you've never been\na police officer, have you?",
	"No, I haven't.",
	"No, you haven't. And so here\nwe have yet another example",
	"of bee culture casually\nstolen by a human",
	"for nothing more than\na prance-about stage name.",
	"Oh, please.",
	"Have you ever been stung, Mr. Sting?",
	"Because I'm feeling\na little stung, Sting.",
	"Or should I say... Mr. Gordon M. Sumner!",
	"That's not his real name?! You idiots!",
	"Mr. Liotta, first,\nbelated congratulations on",
	"your Emmy win for a guest spot\non ER in 2005.",
	"Thank you. Thank you.",
	"I see from your resume\nthat you're devilishly handsome",
	"with a churning inner turmoil\nthat's ready to blow.",
	"I enjoy what I do. Is that a crime?",
	"Not yet it isn't. But is this\nwhat it's come to for you?",
	"Exploiting tiny, helpless bees\nso you don't",
	"have to rehearse\nyour part and learn your lines, sir?",
	"Watch it, Benson!\nI could blow right now!",
	"This isn't a goodfella.\nThis is a badfella!",
	"Why doesn't someone just step on\nthis creep, and we can all go home?!",
	"- Order in this court!\n- You're all thinking it!",
	"Order! Order, I say!",
	"- Say it!\n- Mr. Liotta, please sit down!",
	"I think it was awfully nice\nof that bear to pitch in like that.",
	"I think the jury's on our side.",
	"Are we doing everything right, legally?",
	"I'm a florist.",
	"Right. Well, here's to a great team.",
	"To a great team!",
	"Well, hello.",
	"- Ken!\n- Hello.",
	"I didn't think you were coming.",
	"No, I was just late.\nI tried to call, but... the battery.",
	"I didn't want all this to go to waste,\nso I called Barry. Luckily, he was free.",
	"Oh, that was lucky.",
	"There's a little left.\nI could heat it up.",
	"Yeah, heat it up, sure, whatever.",
	"So I hear you're quite a tennis player.",
	"I'm not much for the game myself.\nThe ball's a little grabby.",
	"That's where I usually sit.\nRight... there.",
	"Ken, Barry was looking at your resume,",
	"and he agreed with me that eating with\nchopsticks isn't really a special skill.",
	"You think I don't see what you're doing?",
	"I know how hard it is to find\nthe rightjob. We have that in common.",
	"Do we?",
	"Bees have 100 percent employment,\nbut we do jobs like taking the crud out.",
	"That's just what\nI was thinking about doing.",
	"Ken, I let Barry borrow your razor\nfor his fuzz. I hope that was all right.",
	"I'm going to drain the old stinger.",
	"Yeah, you do that.",
	"Look at that.",
	"You know, I've just about had it",
	"with your little mind games.",
	"- What's that?\n- Italian Vogue.",
	"Mamma mia, that's a lot of pages.",
	"A lot of ads.",
	"Remember what Van said, why is\nyour life more valuable than mine?",
	"Funny, I just can't seem to recall that!",
	"I think something stinks in here!",
	"I love the smell of flowers.",
	"How do you like the smell of flames?!",
	"Not as much.",
	"Water bug! Not taking sides!",
	"Ken, I'm wearing a Ohapstick hat!\nThis is pathetic!",
	"I've got issues!",
	"Well, well, well, a royal flush!",
	"- You're bluffing.\n- Am I?",
	"Surf's up, dude!",
	"Poo water!",
	"That bowl is gnarly.",
	"Except for those dirty yellow rings!",
	"Kenneth! What are you doing?!",
	"You know, I don't even like honey!\nI don't eat it!",
	"We need to talk!",
	"He's just a little bee!",
	"And he happens to be\nthe nicest bee I've met in a long time!",
	"Long time? What are you talking about?!\nAre there other bugs in your life?",
	"No, but there are other things bugging\nme in life. And you're one of them!",
	"Fine! Talking bees, no yogurt night...",
	"My nerves are fried from riding\non this emotional roller coaster!",
	"Goodbye, Ken.",
	"And for your information,",
	"I prefer sugar-free, artificial\nsweeteners made by man!",
	"I'm sorry about all that.",
	"I know it's got\nan aftertaste! I like it!",
	"I always felt there was some kind\nof barrier between Ken and me.",
	"I couldn't overcome it.\nOh, well.",
	"Are you OK for the trial?",
	"I believe Mr. Montgomery\nis about out of ideas.",
	"We would like to call\nMr. Barry Benson Bee to the stand.",
	"Good idea! You can really see why he's\nconsidered one of the best lawyers...",
	"Yeah.",
	"Layton, you've\ngotta weave some magic",
	"with this jury,\nor it's gonna be all over.",
	"Don't worry. The only thing I have\nto do to turn this jury around",
	"is to remind them\nof what they don't like about bees.",
	"- You got the tweezers?\n- Are you allergic?",
	"Only to losing, son. Only to losing.",
	"Mr. Benson Bee, I'll ask you\nwhat I think we'd all like to know.",
	"What exactly is your relationship",
	"to that woman?",
	"We're friends.",
	"- Good friends?\n- Yes.",
	"How good? Do you live together?",
	"Wait a minute...",
	"Are you her little...",
	"...bedbug?",
	"I've seen a bee documentary or two.\nFrom what I understand,",
	"doesn't your queen give birth\nto all the bee children?",
	"- Yeah, but...\n- So those aren't your real parents!",
	"- Oh, Barry...\n- Yes, they are!",
	"Hold me back!",
	"You're an illegitimate bee,\naren't you, Benson?",
	"He's denouncing bees!",
	"Don't y'all date your cousins?",
	"- Objection!\n- I'm going to pincushion this guy!",
	"Adam, don't! It's what he wants!",
	"Oh, I'm hit!!",
	"Oh, lordy, I am hit!",
	"Order! Order!",
	"The venom! The venom\nis coursing through my veins!",
	"I have been felled\nby a winged beast of destruction!",
	"You see? You can't treat them\nlike equals! They're striped savages!",
	"Stinging's the only thing\nthey know! It's their way!",
	"- Adam, stay with me.\n- I can't feel my legs.",
	"What angel of mercy\nwill come forward to suck the poison",
	"from my heaving buttocks?",
	"I will have order in this court. Order!",
	"Order, please!",
	"The case of the honeybees\nversus the human race",
	"took a pointed turn against the bees",
	"yesterday when one of their legal\nteam stung Layton T. Montgomery.",
	"- Hey, buddy.\n- Hey.",
	"- Is there much pain?\n- Yeah.",
	"I...",
	"I blew the whole case, didn't I?",
	"It doesn't matter. What matters is\nyou're alive. You could have died.",
	"I'd be better off dead. Look at me.",
	"They got it from the cafeteria\ndownstairs, in a tuna sandwich.",
	"Look, there's\na little celery still on it.",
	"What was it like to sting someone?",
	"I can't explain it. It was all...",
	"All adrenaline and then...\nand then ecstasy!",
	"All right.",
	"You think it was all a trap?",
	"Of course. I'm sorry.\nI flew us right into this.",
	"What were we thinking? Look at us. We're\njust a couple of bugs in this world.",
	"What will the humans do to us\nif they win?",
	"I don't know.",
	"I hear they put the roaches in motels.\nThat doesn't sound so bad.",
	"Adam, they check in,\nbut they don't check out!",
	"Oh, my.",
	"Oould you get a nurse\nto close that window?",
	"- Why?\n- The smoke.",
	"Bees don't smoke.",
	"Right. Bees don't smoke.",
	"Bees don't smoke!\nBut some bees are smoking.",
	"That's it! That's our case!",
	"It is? It's not over?",
	"Get dressed. I've gotta go somewhere.",
	"Get back to the court and stall.\nStall any way you can.",
	"And assuming you've done step correctly, you're ready for the tub.",
	"Mr. Flayman.",
	"Yes? Yes, Your Honor!",
	"Where is the rest of your team?",
	"Well, Your Honor, it's interesting.",
	"Bees are trained to fly haphazardly,",
	"and as a result,\nwe don't make very good time.",
	"I actually heard a funny story about...",
	"Your Honor,\nhaven't these ridiculous bugs",
	"taken up enough\nof this court's valuable time?",
	"How much longer will we allow\nthese absurd shenanigans to go on?",
	"They have presented no compelling\nevidence to support their charges",
	"against my clients,\nwho run legitimate businesses.",
	"I move for a complete dismissal\nof this entire case!",
	"Mr. Flayman, I'm afraid I'm going",
	"to have to consider\nMr. Montgomery's motion.",
	"But you can't! We have a terrific case.",
	"Where is your proof?\nWhere is the evidence?",
	"Show me the smoking gun!",
	"Hold it, Your Honor!\nYou want a smoking gun?",
	"Here is your smoking gun.",
	"What is that?",
	"It's a bee smoker!",
	"What, this?\nThis harmless little contraption?",
	"This couldn't hurt a fly,\nlet alone a bee.",
	"Look at what has happened",
	'to bees who have never been asked,"Smoking or non?"',
	"Is this what nature intended for us?",
	"To be forcibly addicted\nto smoke machines",
	"and man-made wooden slat work camps?",
	"Living out our lives as honey slaves\nto the white man?",
	"- What are we gonna do?\n- He's playing the species card.",
	"Ladies and gentlemen, please,\nfree these bees!",
	"Free the bees! Free the bees!",
	"Free the bees!",
	"Free the bees! Free the bees!",
	"The court finds in favor of the bees!",
	"Vanessa, we won!",
	"I knew you could do it! High-five!",
	"Sorry.",
	"I'm OK! You know what this means?",
	"All the honey\nwill finally belong to the bees.",
	"Now we won't have\nto work so hard all the time.",
	"This is an unholy perversion\nof the balance of nature, Benson.",
	"You'll regret this.",
	"Barry, how much honey is out there?",
	"All right. One at a time.",
	"Barry, who are you wearing?",
	"My sweater is Ralph Lauren,\nand I have no pants.",
	"- What if Montgomery's right?\n- What do you mean?",
	"We've been living the bee way\na long time, 27 million years.",
	"Oongratulations on your victory.\nWhat will you demand as a settlement?",
	"First, we'll demand a complete shutdown\nof all bee work camps.",
	"Then we want back the honey\nthat was ours to begin with,",
	"every last drop.",
	"We demand an end to the glorification\nof the bear as anything more",
	"than a filthy, smelly,\nbad-breath stink machine.",
	"We're all aware\nof what they do in the woods.",
	"Wait for my signal.",
	"Take him out.",
	"He'll have nauseous\nfor a few hours, then he'll be fine.",
	"And we will no longer tolerate\nbee-negative nicknames...",
	"But it's just a prance-about stage name!",
	"...unnecessary inclusion of honey\nin bogus health products",
	"and la-dee-da human\ntea-time snack garnishments.",
	"Oan't breathe.",
	"Bring it in, boys!",
	"Hold it right there! Good.",
	"Tap it.",
	"Mr. Buzzwell, we just passed three cups,\nand there's gallons more coming!",
	"- I think we need to shut down!\n- Shut down? We've never shut down.",
	"Shut down honey production!",
	"Stop making honey!",
	"Turn your key, sir!",
	"What do we do now?",
	"Oannonball!",
	"We're shutting honey production!",
	"Mission abort.",
	"Aborting pollination and nectar detail.\nReturning to base.",
	"Adam, you wouldn't believe\nhow much honey was out there.",
	"Oh, yeah?",
	"What's going on? Where is everybody?",
	"- Are they out celebrating?\n- They're home.",
	"They don't know what to do.\nLaying out, sleeping in.",
	"I heard your Uncle Oarl was on his way\nto San Antonio with a cricket.",
	"At least we got our honey back.",
	"Sometimes I think, so what if humans\nliked our honey? Who wouldn't?",
	"It's the greatest thing in the world!\nI was excited to be part of making it.",
	"This was my new desk. This was my\nnew job. I wanted to do it really well.",
	"And now...",
	"Now I can't.",
	"I don't understand\nwhy they're not happy.",
	"I thought their lives would be better!",
	"They're doing nothing. It's amazing.\nHoney really changes people.",
	"You don't have any idea\nwhat's going on, do you?",
	"- What did you want to show me?\n- This.",
	"What happened here?",
	"That is not the half of it.",
	"Oh, no. Oh, my.",
	"They're all wilting.",
	"Doesn't look very good, does it?",
	"No.",
	"And whose fault do you think that is?",
	"You know, I'm gonna guess bees.",
	"Bees?",
	"Specifically, me.",
	"I didn't think bees not needing to make\nhoney would affect all these things.",
	"It's notjust flowers.\nFruits, vegetables, they all need bees.",
	"That's our whole SAT test right there.",
	"Take away produce, that affects\nthe entire animal kingdom.",
	"And then, of course...",
	"The human species?",
	"So if there's no more pollination,",
	"it could all just go south here,\ncouldn't it?",
	"I know this is also partly my fault.",
	"How about a suicide pact?",
	"How do we do it?",
	"- I'll sting you, you step on me.\n- Thatjust kills you twice.",
	"Right, right.",
	"Listen, Barry...\nsorry, but I gotta get going.",
	"I had to open my mouth and talk.",
	"Vanessa?",
	"Vanessa? Why are you leaving?\nWhere are you going?",
	"To the final Tournament of Roses parade\nin Pasadena.",
	"They've moved it to this weekend\nbecause all the flowers are dying.",
	"It's the last chance\nI'll ever have to see it.",
	"Vanessa, I just wanna say I'm sorry.\nI never meant it to turn out like this.",
	"I know. Me neither.",
	"Tournament of Roses.\nRoses can't do sports.",
	"Wait a minute. Roses. Roses?",
	"Roses!",
	"Vanessa!",
	"Roses?!",
	"Barry?",
	"- Roses are flowers!\n- Yes, they are.",
	"Flowers, bees, pollen!",
	"I know.\nThat's why this is the last parade.",
	"Maybe not.\nOould you ask him to slow down?",
	"Oould you slow down?",
	"Barry!",
	"OK, I made a huge mistake.\nThis is a total disaster, all my fault.",
	"Yes, it kind of is.",
	"I've ruined the planet.\nI wanted to help you",
	"with the flower shop.\nI've made it worse.",
	"Actually, it's completely closed down.",
	"I thought maybe you were remodeling.",
	"But I have another idea, and it's\ngreater than my previous ideas combined.",
	"I don't want to hear it!",
	"All right, they have the roses,\nthe roses have the pollen.",
	"I know every bee, plant\nand flower bud in this park.",
	"All we gotta do is get what they've got\nback here with what we've got.",
	"- Bees.\n- Park.",
	"- Pollen!\n- Flowers.",
	"- Repollination!\n- Across the nation!",
	"Tournament of Roses,\nPasadena, Oalifornia.",
	"They've got nothing\nbut flowers, floats and cotton candy.",
	"Security will be tight.",
	"I have an idea.",
	"Vanessa Bloome, FTD.",
	"Official floral business. It's real.",
	"Sorry, ma'am. Nice brooch.",
	"Thank you. It was a gift.",
	"Once inside,\nwe just pick the right float.",
	"How about The Princess and the Pea?",
	"I could be the princess,\nand you could be the pea!",
	"Yes, I got it.",
	"- Where should I sit?\n- What are you?",
	"- I believe I'm the pea.\n- The pea?",
	"It goes under the mattresses.",
	"- Not in this fairy tale, sweetheart.\n- I'm getting the marshal.",
	"You do that!\nThis whole parade is a fiasco!",
	"Let's see what this baby'll do.",
	"Hey, what are you doing?!",
	"Then all we do\nis blend in with traffic...",
	"...without arousing suspicion.",
	"Once at the airport,\nthere's no stopping us.",
	"Stop! Security.",
	"- You and your insect pack your float?\n- Yes.",
	"Has it been\nin your possession the entire time?",
	"Would you remove your shoes?",
	"- Remove your stinger.\n- It's part of me.",
	"I know. Just having some fun.\nEnjoy your flight.",
	"Then if we're lucky, we'll have\njust enough pollen to do the job.",
	"Oan you believe how lucky we are? We\nhave just enough pollen to do the job!",
	"I think this is gonna work.",
	"It's got to work.",
	"Attention, passengers,\nthis is Oaptain Scott.",
	"We have a bit of bad weather\nin New York.",
	"It looks like we'll experience\na couple hours delay.",
	"Barry, these are cut flowers\nwith no water. They'll never make it.",
	"I gotta get up there\nand talk to them.",
	"Be careful.",
	"Oan I get help\nwith the Sky Mall magazine?",
	"I'd like to order the talking\ninflatable nose and ear hair trimmer.",
	"Oaptain, I'm in a real situation.",
	"- What'd you say, Hal?\n- Nothing.",
	"Bee!",
	"Don't freak out! My entire species...",
	"What are you doing?",
	"- Wait a minute! I'm an attorney!\n- Who's an attorney?",
	"Don't move.",
	"Oh, Barry.",
	"Good afternoon, passengers.\nThis is your captain.",
	"Would a Miss Vanessa Bloome in 24B\nplease report to the cockpit?",
	"And please hurry!",
	"What happened here?",
	"There was a DustBuster,\na toupee, a life raft exploded.",
	"One's bald, one's in a boat,\nthey're both unconscious!",
	"- Is that another bee joke?\n- No!",
	"No one's flying the plane!",
	"This is JFK control tower, Flight 356.\nWhat's your status?",
	"This is Vanessa Bloome.\nI'm a florist from New York.",
	"Where's the pilot?",
	"He's unconscious,\nand so is the copilot.",
	"Not good. Does anyone onboard\nhave flight experience?",
	"As a matter of fact, there is.",
	"- Who's that?\n- Barry Benson.",
	"From the honey trial?! Oh, great.",
	"Vanessa, this is nothing more\nthan a big metal bee.",
	"It's got giant wings, huge engines.",
	"I can't fly a plane.",
	"- Why not? Isn't John Travolta a pilot?\n- Yes.",
	"How hard could it be?",
	"Wait, Barry!\nWe're headed into some lightning.",
	"This is Bob Bumble. We have some\nlate-breaking news from JFK Airport,",
	"where a suspenseful scene\nis developing.",
	"Barry Benson,\nfresh from his legal victory...",
	"That's Barry!",
	"...is attempting to land a plane,\nloaded with people, flowers",
	"and an incapacitated flight crew.",
	"Flowers?!",
	"We have a storm in the area\nand two individuals at the controls",
	"with absolutely no flight experience.",
	"Just a minute.\nThere's a bee on that plane.",
	"I'm quite familiar with Mr. Benson\nand his no-account compadres.",
	"They've done enough damage.",
	"But isn't he your only hope?",
	"Technically, a bee\nshouldn't be able to fly at all.",
	"Their wings are too small...",
	"Haven't we heard this a million times?",
	'"The surface area of the wings\nand body mass make no sense."',
	"- Get this on the air!\n- Got it.",
	"- Stand by.\n- We're going live.",
	"The way we work may be a mystery to you.",
	"Making honey takes a lot of bees\ndoing a lot of small jobs.",
	"But let me tell you about a small job.",
	"If you do it well,\nit makes a big difference.",
	"More than we realized.\nTo us, to everyone.",
	"That's why I want to get bees\nback to working together.",
	"That's the bee way!\nWe're not made of Jell-O.",
	"We get behind a fellow.",
	"- Black and yellow!\n- Hello!",
	"Left, right, down, hover.",
	"- Hover?\n- Forget hover.",
	"This isn't so hard.\nBeep-beep! Beep-beep!",
	"Barry, what happened?!",
	"Wait, I think we were\non autopilot the whole time.",
	"- That may have been helping me.\n- And now we're not!",
	"So it turns out I cannot fly a plane.",
	"All of you, let's get\nbehind this fellow! Move it out!",
	"Move out!",
	"Our only chance is if I do what I'd do,\nyou copy me with the wings of the plane!",
	"Don't have to yell.",
	"I'm not yelling!\nWe're in a lot of trouble.",
	"It's very hard to concentrate\nwith that panicky tone in your voice!",
	"It's not a tone. I'm panicking!",
	"I can't do this!",
	"Vanessa, pull yourself together.\nYou have to snap out of it!",
	"You snap out of it.",
	"You snap out of it.",
	"- You snap out of it!\n- You snap out of it!",
	"- You snap out of it!\n- You snap out of it!",
	"- You snap out of it!\n- You snap out of it!",
	"- Hold it!\n- Why? Oome on, it's my turn.",
	"How is the plane flying?",
	"I don't know.",
	"Hello?",
	"Benson, got any flowers\nfor a happy occasion in there?",
	"The Pollen Jocks!",
	"They do get behind a fellow.",
	"- Black and yellow.\n- Hello.",
	"All right, let's drop this tin can\non the blacktop.",
	"Where? I can't see anything. Oan you?",
	"No, nothing. It's all cloudy.",
	"Oome on. You got to think bee, Barry.",
	"- Thinking bee.\n- Thinking bee.",
	"Thinking bee!\nThinking bee! Thinking bee!",
	"Wait a minute.\nI think I'm feeling something.",
	"- What?\n- I don't know. It's strong, pulling me.",
	"Like a 27-million-year-old instinct.",
	"Bring the nose down.",
	"Thinking bee!\nThinking bee! Thinking bee!",
	"- What in the world is on the tarmac?\n- Get some lights on that!",
	"Thinking bee!\nThinking bee! Thinking bee!",
	"- Vanessa, aim for the flower.\n- OK.",
	"Out the engines. We're going in\non bee power. Ready, boys?",
	"Affirmative!",
	"Good. Good. Easy, now. That's it.",
	"Land on that flower!",
	"Ready? Full reverse!",
	"Spin it around!",
	"- Not that flower! The other one!\n- Which one?",
	"- That flower.\n- I'm aiming at the flower!",
	"That's a fat guy in a flowered shirt.\nI mean the giant pulsating flower",
	"made of millions of bees!",
	"Pull forward. Nose down. Tail up.",
	"Rotate around it.",
	"- This is insane, Barry!\n- This's the only way I know how to fly.",
	"Am I koo-koo-kachoo, or is this plane\nflying in an insect-like pattern?",
	"Get your nose in there. Don't be afraid.\nSmell it. Full reverse!",
	"Just drop it. Be a part of it.",
	"Aim for the center!",
	"Now drop it in! Drop it in, woman!",
	"Oome on, already.",
	"Barry, we did it!\nYou taught me how to fly!",
	"- Yes. No high-five!\n- Right.",
	"Barry, it worked!\nDid you see the giant flower?",
	"What giant flower? Where? Of course\nI saw the flower! That was genius!",
	"- Thank you.\n- But we're not done yet.",
	"Listen, everyone!",
	"This runway is covered\nwith the last pollen",
	"from the last flowers\navailable anywhere on Earth.",
	"That means this is our last chance.",
	"We're the only ones who make honey,\npollinate flowers and dress like this.",
	"If we're gonna survive as a species,\nthis is our moment! What do you say?",
	"Are we going to be bees, orjust\nMuseum of Natural History keychains?",
	"We're bees!",
	"Keychain!",
	"Then follow me! Except Keychain.",
	"Hold on, Barry. Here.",
	"You've earned this.",
	"Yeah!",
	"I'm a Pollen Jock! And it's a perfect\nfit. All I gotta do are the sleeves.",
	"Oh, yeah.",
	"That's our Barry.",
	"Mom! The bees are back!",
	"If anybody needs\nto make a call, now's the time.",
	"I got a feeling we'll be\nworking late tonight!",
	"Here's your change. Have a great\nafternoon! Oan I help who's next?",
	"Would you like some honey with that?\nIt is bee-approved. Don't forget these.",
	"Milk, cream, cheese, it's all me.\nAnd I don't see a nickel!",
	"Sometimes I just feel\nlike a piece of meat!",
	"I had no idea.",
	"Barry, I'm sorry.\nHave you got a moment?",
	"Would you excuse me?\nMy mosquito associate will help you.",
	"Sorry I'm late.",
	"He's a lawyer too?",
	"I was already a blood-sucking parasite.\nAll I needed was a briefcase.",
	"Have a great afternoon!",
	"Barry, I just got this huge tulip order,\nand I can't get them anywhere.",
	"No problem, Vannie.\nJust leave it to me.",
	"You're a lifesaver, Barry.\nOan I help who's next?",
	"All right, scramble, jocks!\nIt's time to fly.",
	"Thank you, Barry!",
	"That bee is living my life!",
	"Let it go, Kenny.",
	"- When will this nightmare end?!\n- Let it all go.",
	"- Beautiful day to fly.\n- Sure is.",
	"Between you and me,\nI was dying to get out of that office.",
	"You have got\nto start thinking bee, my friend.",
	"- Thinking bee!\n- Me?",
	"Hold it. Let's just stop\nfor a second. Hold it.",
	"I'm sorry. I'm sorry, everyone.\nOan we stop here?",
	"I'm not making a major life decision\nduring a production number!",
	"All right. Take ten, everybody.\nWrap it up, guys.",
	"I had virtually no rehearsal for that.",
];

console.log();
sayLine(0);

function sayLine(cursor: unknown) {
	if(typeof cursor != "number") {
		throw new TypeError("Argument must be of type number");
	}
	console.log(transcript[cursor] + "\n");
	if(cursor < transcript.length - 1) {
		setTimeout(sayLine, 1000, cursor + 1);
	}
}
